table faixas
	lineageTag: 17c81226-2924-481f-aa9c-5e2ac94191c0

	measure 'Clientes por Faixas' = ```
			
			
			VAR __source =
			    ADDCOLUMNS (
				    VALUES ( vendas[Cliente_ID] ),
			        "@Media", [Média dias entre vendas por cliente]
			    )
			
			VAR __faixas = 
			    ADDCOLUMNS (
			        faixas,
			        "@Clientes",
			        COUNTROWS (
			            FILTER ( 
			                __source,
			                [@Media] >= faixas[Min] &&
			                [@Media] <  faixas[Max]
			            )
			        )
			    )
			
			RETURN
			    SUMX ( __faixas, [@Clientes] )
			    
			```
		formatString: 0
		displayFolder: Medidas
		lineageTag: dadbad88-f541-4dcb-b680-ca4a14cfa2bd

	column Min
		formatString: 0
		displayFolder: Colunas
		lineageTag: bf9c55d0-cc26-46ed-88d6-573c89ab0e95
		summarizeBy: none
		isNameInferred
		sourceColumn: [Min]

		annotation SummarizationSetBy = User

	column Max
		formatString: 0
		displayFolder: Colunas
		lineageTag: b8e79895-405c-45e1-9721-a740c0577562
		summarizeBy: none
		isNameInferred
		sourceColumn: [Max]

		annotation SummarizationSetBy = User

	column Faixa
		displayFolder: Colunas
		lineageTag: 5dd2b161-76a5-4b75-bbb9-79f9d55600ca
		summarizeBy: none
		isNameInferred
		sourceColumn: [Faixa]
		sortByColumn: Min

		annotation SummarizationSetBy = Automatic

	partition faixas = calculated
		mode: import
		source = ```
				
				    ADDCOLUMNS(
				        UNION(
				            SELECTCOLUMNS(
				                GENERATESERIES(
				                    0,
				                    1600,
				                    10
				                ),
				                "Min", [Value],
				                "Max", [Value] + 10
				            ),
				            {(1610, 999999)}
				        ),
				        "Faixa", 
				        SWITCH( TRUE(), 
				            [Min] = 0, "<" & [Max],
				            [Max] = 999999, [Min] & "+",
				            [Min] & "~" & [Max]
				        )
				    )
				```

	annotation PBI_Id = d4104f124f4c474c85e2a739601fffce

