table vendas
	lineageTag: b65658fa-3450-4bfb-a24d-f7417e0ea5b2

	measure 'Média dias entre vendas por cliente' = ```
			
			AVERAGEX(
			    vendas,
			    DATEDIFF(vendas[VendaAnteriorDoCliente], vendas[Data], DAY)
			) 
			
			    
			```
		displayFolder: Medidas
		lineageTag: a0223db8-e01b-446a-9d69-b7af378477fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média dias entre vendas por cliente (ALLSELECTED)' = ```
			
				CALCULATE (
			        [Média dias entre vendas por cliente],
			        ALLSELECTED ( vendas[Cliente_ID] )
			    ) 
			```
		displayFolder: Medidas
		lineageTag: 5cb08fe3-1c44-41e7-bc86-c12a4583726e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Venda_ID
		dataType: int64
		formatString: 0
		displayFolder: Colunas\ID's
		lineageTag: 4f9e5e1f-d28b-4647-ad6d-c185eba1851d
		summarizeBy: none
		sourceColumn: Venda_ID

		annotation SummarizationSetBy = User

	column Data
		dataType: dateTime
		formatString: Short Date
		displayFolder: Colunas\ID's
		lineageTag: 04851672-df47-41d8-b216-33e8e2bef40b
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Cliente_ID
		dataType: int64
		formatString: 0
		displayFolder: Colunas\ID's
		lineageTag: 3133586e-073d-4b71-b326-0e3aed87b073
		summarizeBy: none
		sourceColumn: Cliente_ID

		annotation SummarizationSetBy = User

	column Loja_ID
		dataType: int64
		formatString: 0
		displayFolder: Colunas\ID's
		lineageTag: 7ee9de34-0a5c-4acb-ab14-8422b6512f52
		summarizeBy: none
		sourceColumn: Loja_ID

		annotation SummarizationSetBy = User

	column Produto_ID
		dataType: int64
		formatString: 0
		displayFolder: Colunas\ID's
		lineageTag: c2621ae0-d152-4590-a7cc-e4d95ad89295
		summarizeBy: none
		sourceColumn: Produto_ID

		annotation SummarizationSetBy = User

	column Valor
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: Colunas\Valores
		lineageTag: 125a930e-6f27-412a-a891-80d4f45cbfc1
		summarizeBy: none
		sourceColumn: Valor

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column VendaAnteriorDoCliente = ```
			
			    COALESCE(
			        SELECTCOLUMNS(
			            OFFSET(
			                -1,
			                ALL(vendas[Cliente_ID], vendas[Venda_ID], vendas[Data]),
			                ORDERBY([Data]),
			                PARTITIONBY(vendas[Cliente_ID])
			            ),
			            [Data]
			        ),
			        [Data]
			    )
			
			```
		formatString: General Date
		displayFolder: Colunas Calculadas
		lineageTag: 6614aa98-6631-4c91-a37a-f731208b15cd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition vendas = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("BOOK-PROIJR07F2", "sandbox"),
				    dbo_vendas = Fonte{[Schema="dbo",Item="vendas"]}[Data]
				in
				    dbo_vendas

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

